# Generated by Django 3.1.4 on 2020-12-27 21:14

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='categorias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='O seu nome completo', max_length=150)),
                ('data_nascimento', models.CharField(help_text='Por favor use "-" para DD-MM-AAAA', max_length=10)),
                ('endereco', models.CharField(help_text='O seu endereço residêncial', max_length=250)),
                ('telefone', phone_field.models.PhoneField(blank=True, help_text='Telefone para contato', max_length=31)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'categorias',
            },
        ),
        migrations.DeleteModel(
            name='categoria',
        ),
    ]
