# Generated by Django 3.1.4 on 2020-12-27 22:01

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0002_auto_20201227_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorias',
            name='endereco',
            field=models.CharField(help_text='O seu endereço residêncial (País. Estado. Cidade. Endereço. Número. cep)', max_length=250),
        ),
        migrations.AlterField(
            model_name='categorias',
            name='telefone',
            field=phone_field.models.PhoneField(help_text='Telefone para contato ((XX) XXXXX-XXXX)', max_length=11),
        ),
    ]
